### ISSUE TITLE
似乎现在(2019/08/01)，注册NSwagger之后，不能正常打开SwaggerUI界面。

### ISSUE THREAD

**Issue by liu595108672** [aspnet/AspNetCore.Docs.zh-cn#158]
在Nuget中已经找不到  `Microsoft.AspNetCore.Mvc.NewtonsoftJson`  这个包了，Swagger似乎要用到这个东西

浏览器页面上提示
```
Fetch error
Internal Server Error /swagger/v1/swagger.json

```

VS中有关异常的提示：
```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview7-27912-14\Microsoft.CSharp.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\3.0.0-preview7.19365.7\Microsoft.AspNetCore.Mvc.Formatters.Json.dll'. 
Exception thrown: 'System.TypeLoadException' in NSwag.Generation.AspNetCore.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in NSwag.AspNetCore.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview7-27912-14\System.Diagnostics.StackTrace.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview7-27912-14\System.Reflection.Metadata.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview7-27912-14\System.Collections.Immutable.dll'. 
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GetJsonSerializerSettings(IServiceProvider serviceProvider)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(Object serviceProvider)
   at NSwag.AspNetCore.OpenApiDocumentProvider.GenerateAsync(String documentName)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)


Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 605.9249ms 500 text/plain
```

**Comment by srvbpigh** [comment]
Hello, @liu595108672
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by liu595108672** [comment]
> 
> 
> Hello, @liu595108672
> 
> Thank you for your feedback.
> 
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards,
> Microsoft DOCS International Team

Sorry, it's my fault.
I didn't include prerelease version while searching for nuget package.

When I include prerelease version, I find the package and now it works
